name: YGO Combo Maker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache (force)
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native modules
        run: npm rebuild lightningcss

      - name: Run Linter
        run: npm run lint

      - name: Build Project
        run: npm run build
